### ISSUE TITLE
Upgrade Capacitor

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/cs-demo-ac-providers#3]
1.5.1 does not support Xcode 11.4, we need to have 1.5.2 or higher

**Comment by kensodemann** [comment]
Since this likely involves rebuilding the iOS project from scratch, remember to put `msauth` in the proper part of the `Info.plist` file.

**Comment by ehorodyski-ionic** [comment]
PR raised: https://github.com/ionic-team/cs-demo-ac-providers/pull/4
